version: '3'
services:

  db:
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: read_gurbani_root_password
      MYSQL_DATABASE: read_gurbani_db
      MYSQL_USER: read_gurbami_admin
      MYSQL_PASSWORD: read_gurbani_password

  web:
    build: .
    volumes:
        - ./:/var/www/site
    ports:
      - 8080:80
    environment:
      APP_DEBUG: "true"
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: read_gurbami_admin
      MYSQL_PASSWORD: read_gurbani_password
      MYSQL_ROOT_PASSWORD: read_gurbani_root_password
    ports:
      - "8181:80"
    links:
      # for mysql container
      - "db:db"
volumes:
    db:
      driver: "local"
